#!/usr/bin/env bash
# === 1. File Header ===
#
# retag-push.sh - load every docker image tar in a directory, retag it under a
# new registry prefix (flattening the repo path), and push it.
#
# Usage:
#   ./retag-push.sh <tar_dir> <target_prefix> [--cleanup] [--dry-run]
#
#   tar_dir        directory containing *.tar / *.tar.gz / *.tgz (top level only)
#   target_prefix  e.g. harbor.example.com/myproject  ->  harbor.example.com/myproject/<name>:<tag>
#   --cleanup      after a successful push, remove both local tags
#   --dry-run      show what would happen; reads manifest.json instead of loading
#
# Exit codes: 0 all tars succeeded, 1 at least one tar failed or docker
# unreachable, 2 usage error, 127 missing dependency.
# Assumes `docker login` was already done; credentials are never handled here.
#
# Dependencies: bash >= 3.2, tar, sort (with -z), docker (not needed for --dry-run)
# Tested on:    macOS / bash 3.2 (dry-run paths); push paths need a real daemon

# No -e on purpose: per-tar failures are recorded and the run continues, so
# every external call is checked explicitly instead.
set -uo pipefail

# Cron and other non-interactive shells ship a minimal PATH. Append (not
# replace) so a user's own docker location still wins.
export PATH="${PATH}:/usr/local/bin:/usr/bin:/bin"

# === 2. Constants (readonly, UPPER_CASE) ===
readonly EXIT_OK=0
readonly EXIT_FAILED=1
readonly EXIT_USAGE=2
readonly EXIT_MISSING_DEP=127

# Runtime configuration, filled once by parse_args and read-only afterwards.
TAR_DIR=""
TARGET_PREFIX=""
CLEANUP=0
DRY_RUN=0

# === 3. Functions (snake_case, every variable local) ===

# Arguments: $@ = message
# Returns:   0
# Side effects: writes to stdout (log) or stderr (warn, err)
log()  { printf '%s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
err()  { printf 'ERROR: %s\n' "$*" >&2; }

# Arguments: none
# Returns:   does not return; exits with EXIT_USAGE
# Side effects: prints the header comment block of this file to stderr
usage() {
  sed -n '3,/^$/p' "$0" | sed 's/^# \{0,1\}//' >&2
  exit "$EXIT_USAGE"
}

# Arguments: $1 = command name
# Returns:   0 if found; exits with EXIT_MISSING_DEP otherwise
# Side effects: none
require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { err "$1 is required"; exit "$EXIT_MISSING_DEP"; }
}

# Map a source image reference to its target by keeping only the last path
# segment. When that segment carries no real tag (none, or `:latest`) and its
# name contains an underscore, the part after the LAST underscore becomes the
# tag:
#   registry.example.com/team/foo:1.2.3 -> $TARGET_PREFIX/foo:1.2.3
#   team/foo                            -> $TARGET_PREFIX/foo:latest
#   team/foo_bar                        -> $TARGET_PREFIX/foo:bar
#   team/foo_bar:latest                 -> $TARGET_PREFIX/foo:bar
#   team/foo_bar_baz                    -> $TARGET_PREFIX/foo_bar:baz
#   team/foo_bar:1.2.3                  -> $TARGET_PREFIX/foo_bar:1.2.3  (explicit tag wins)
#   foo@sha256:abcd...                  -> refused (return 1); digests can't be retagged
# Arguments: $1 = source image reference
# Returns:   0 and prints the target reference; 1 if the source is a digest
# Side effects: none
to_target_ref() {
  local src="$1"
  local last="${src##*/}"
  local name tag
  case "$last" in
    *@*) return 1 ;;
    *:*) name="${last%:*}"; tag="${last##*:}" ;;
    *)   name="$last";      tag="latest" ;;
  esac
  if [[ "$tag" == "latest" && "$name" == *_* ]]; then
    tag="${name##*_}"
    name="${name%_*}"
  fi
  printf '%s/%s:%s\n' "$TARGET_PREFIX" "$name" "$tag"
}

# Print source refs recorded in a tar's manifest.json without loading it
# (dry-run only). Deliberately grep-based so jq is not a dependency; the
# manifest is generated by docker and its RepoTags values never contain
# quotes or escapes.
# Arguments: $1 = tar file path
# Returns:   pipeline status; prints one ref per line (may be empty)
# Side effects: none
refs_from_manifest() {
  local tar_file="$1"
  tar -xOf "$tar_file" manifest.json 2>/dev/null \
    | grep -o '"RepoTags":\[[^]]*\]' \
    | grep -o '"[^"]*"' \
    | grep -v '"RepoTags"' \
    | tr -d '"'
}

# Print source refs produced by `docker load`.
# Arguments: $1 = tar file path
# Returns:   0 and prints one ref per line; 1 on load failure or if any image
#            in the tar was unnamed (saved by ID)
# Side effects: loads images into the local docker daemon
refs_from_load() {
  local tar_file="$1"
  local out rc=0
  out=$(docker load -i "$tar_file") || return 1
  if grep -q '^Loaded image ID:' <<<"$out"; then
    err "  tar contains unnamed image(s), cannot retag"
    rc=1
  fi
  sed -n 's/^Loaded image: //p' <<<"$out"
  return "$rc"
}

# Retag and push one image.
# Arguments: $1 = source image reference
# Returns:   0 on success; 1 on any failure
# Side effects: docker tag / push; docker rmi of both tags when CLEANUP=1.
#               Only logs when DRY_RUN=1.
process_image() {
  local src="$1"
  local dst

  if ! dst=$(to_target_ref "$src"); then
    err "  cannot map $src"
    return 1
  fi
  log "  $src -> $dst"

  if (( DRY_RUN )); then
    return 0
  fi

  if docker image inspect "$dst" >/dev/null 2>&1; then
    warn "  $dst already exists locally, will be overwritten"
  fi
  if ! docker tag "$src" "$dst"; then
    err "  tag failed: $src -> $dst"
    return 1
  fi
  if ! docker push "$dst"; then
    err "  push failed: $dst"
    return 1
  fi
  if (( CLEANUP )); then
    docker rmi "$dst" "$src" >/dev/null || warn "  cleanup failed for $src"
  fi
  return 0
}

# Process every image in one tar.
# Arguments: $1 = tar file path
# Returns:   0 if every image succeeded; 1 if anything in it failed
# Side effects: see refs_from_load and process_image
process_tar() {
  local tar_file="$1"
  local refs src tar_ok=1

  log "==> $(basename "$tar_file")"

  if (( DRY_RUN )); then
    refs=$(refs_from_manifest "$tar_file")
    if [[ -z "$refs" ]]; then
      err "  no RepoTags in manifest.json"
      tar_ok=0
    fi
  else
    refs=$(refs_from_load "$tar_file") || tar_ok=0
  fi

  while IFS= read -r src; do
    [[ -n "$src" ]] || continue
    process_image "$src" || tar_ok=0
  done <<<"$refs"

  (( tar_ok ))
}

# Arguments: $@ = the script's command line
# Returns:   0; exits with EXIT_USAGE on any usage error
# Side effects: sets TAR_DIR, TARGET_PREFIX, CLEANUP, DRY_RUN
parse_args() {
  local arg
  for arg in "$@"; do
    case "$arg" in
      --cleanup) CLEANUP=1 ;;
      --dry-run) DRY_RUN=1 ;;
      -h|--help) usage ;;
      -*) err "unknown option: $arg"; usage ;;
      *)
        if [[ -z "$TAR_DIR" ]]; then
          TAR_DIR="$arg"
        elif [[ -z "$TARGET_PREFIX" ]]; then
          TARGET_PREFIX="$arg"
        else
          err "too many arguments"; usage
        fi
        ;;
    esac
  done

  [[ -n "$TAR_DIR" && -n "$TARGET_PREFIX" ]] || usage
  [[ -d "$TAR_DIR" ]] || { err "not a directory: $TAR_DIR"; exit "$EXIT_USAGE"; }
  TARGET_PREFIX="${TARGET_PREFIX%/}"   # tolerate trailing slash
}

# Arguments: none (reads DRY_RUN)
# Returns:   0; exits with EXIT_MISSING_DEP or EXIT_FAILED otherwise
# Side effects: none
preflight() {
  require_cmd tar
  require_cmd sort
  if (( ! DRY_RUN )); then
    require_cmd docker
    docker info >/dev/null 2>&1 || { err "docker daemon not reachable"; exit "$EXIT_FAILED"; }
  fi
}

# Print the tar files to process, NUL-delimited and sorted by name, so
# filenames with spaces or newlines survive. Top level only, three extensions.
# Arguments: $1 = directory
# Returns:   0 and prints NUL-delimited paths; 1 if none were found
# Side effects: none
list_tar_files() {
  local dir="$1"
  local f found=0
  shopt -s nullglob
  for f in "$dir"/*.tar "$dir"/*.tar.gz "$dir"/*.tgz; do
    printf '%s\0' "$f"
    found=1
  done
  shopt -u nullglob
  (( found )) || return 1
}

# Arguments: $1 = label, $@ = paths
# Returns:   0
# Side effects: writes to stdout
print_list() {
  local label="$1"; shift
  local f
  log "$label ${#@}"
  for f in "$@"; do log "  $(basename "$f")"; done
}

# === 4. Main Logic ===
main() {
  local tar_file
  local sorted_files=() succeeded=() failed=()

  parse_args "$@"
  preflight

  while IFS= read -r -d '' tar_file; do
    sorted_files+=("$tar_file")
  done < <(list_tar_files "$TAR_DIR" | sort -z)
  (( ${#sorted_files[@]} )) || { err "no tar files found in $TAR_DIR"; exit "$EXIT_FAILED"; }

  for tar_file in "${sorted_files[@]}"; do
    if process_tar "$tar_file"; then
      succeeded+=("$tar_file")
    else
      failed+=("$tar_file")
    fi
  done

  # ${arr[@]+"${arr[@]}"} keeps set -u happy on an empty array under bash 3.2.
  log
  print_list "Succeeded:" ${succeeded[@]+"${succeeded[@]}"}
  print_list "Failed:   " ${failed[@]+"${failed[@]}"}

  (( ${#failed[@]} == 0 )) && exit "$EXIT_OK" || exit "$EXIT_FAILED"
}

# Guarded so `source retag-push.sh` in a test loads the functions without
# running anything.
[[ "${BASH_SOURCE[0]}" != "$0" ]] || main "$@"
